import test from 'node:test';
import assert from 'node:assert/strict';
import { RAC_CAUSE_CATALOG, classifyCauseFromCatalog, subtypeByReference } from '../server/racCauseCatalog.js';

const EXPECTED=[
  'CONSUMO DE AGUA','CONSUMO DE ENERGÍA ELÉCTRICA','CONSUMO DE HIDROCARBUROS','CONSUMO DE MADERA','CONSUMO DE PAPEL','CONSUMO DE AIRE COMPRIMIDO','GENERACIÓN DE AGUAS ÁCIDAS O CONTAMINADAS','DERRAME DE SUSTANCIAS PELIGROSAS (QUÍMICOS E HIDROCARBUROS)','GENERACIÓN Y DISPOSICIÓN DE DESMONTE, LODOS Y LAMAS','GENERACIÓN Y DISPOSICIÓN DE RESIDUOS','DISPOSICIÓN DE MINERAL','DERRAME DE RELAVES O SOLUCIONES CIANURADAS','EMISIÓN DE RUIDO','EMISIÓN DE VIBRACIÓN','EMISIÓN DE POLVO Y/O PARTÍCULAS','EMISIÓN DE CALOR','EMISIÓN DE RADIACIÓN','EMISIÓN DE GASES, VAPORES Y/O HUMOS','EXTRACCIÓN DE MINERAL','FUGA DE AGUA Y DESAGÜE','FUGA DE GLP','GENERACIÓN Y DISPOSICIÓN FINAL DE HIDROCARBUROS USADOS Y EN DESUSO','POTENCIAL EMISIÓN DE GASES TÓXICOS','POTENCIAL COLAPSO DE PRESA DE RELAVES','POTENCIAL DERRAME DE AGUA DE LA PRESA DE RELAVES, PULPA O SOLUCIÓN CIANURADA','POTENCIAL DERRAME DE SUSTANCIAS QUÍMICAS Y/O PELIGROSAS','POTENCIAL DERRAME DE HIDROCARBUROS EN USO, DESUSO Y USADOS','POTENCIAL DERRAME DE ACEITES DIELÉCTRICOS','POTENCIAL DERRAME DE CONCENTRADOS','POTENCIAL DERRAME DE LODOS Y/O LAMAS','POTENCIAL DERRAME DE MINERAL','POTENCIAL DERRAME DE RELAVES','POTENCIAL DERRAME DE EFLUENTES LÍQUIDOS CON PARÁMETROS QUE EXCEDEN LOS LMP','POTENCIAL DERRAME DE CAL','POTENCIAL EROSIÓN','REMOCIÓN DE SUELOS','POTENCIAL INCENDIO','POTENCIAL DERRUMBE','POTENCIAL FALLA DE INSTALACIONES E INFRAESTRUCTURA','POTENCIAL INUNDACIÓN','POTENCIAL DERRAME DE RESIDUOS SÓLIDOS DURANTE SU DISPOSICIÓN','POTENCIAL FALLA DE CIERRE DE COMPONENTES','POTENCIAL FALLA DE ESTRUCTURAS HIDRÁULICAS','POTENCIAL FALTA DE GERMINACIÓN','POTENCIAL GENERACIÓN DE LIXIVIADOS','POTENCIAL HUNDIMIENTO','POTENCIAL ROTURA DE GEOMEMBRANA DE LA PRESA DE RELAVES','FORESTACIÓN / REFORESTACIÓN','PLANES DE CIERRE'
];

test('4.0.41 incorpora X ASPECTOS AMBIENTALES con las 49 subcausas en orden',()=>{
  const category=RAC_CAUSE_CATALOG.find(item=>item.code==='X');
  assert.ok(category);
  assert.equal(category.name,'ASPECTOS AMBIENTALES');
  assert.equal(category.reportType,'CONDICION SUBESTANDAR');
  assert.deepEqual(category.subtypes,EXPECTED);
});

test('4.0.41 resuelve subcausas ambientales por coincidencia normalizada',()=>{
  const found=subtypeByReference('Potencial derrame de aceites dielectricos');
  assert.equal(found?.category.code,'X');
  assert.equal(found?.name,'POTENCIAL DERRAME DE ACEITES DIELÉCTRICOS');
  const classified=classifyCauseFromCatalog('Forestacion / reforestacion');
  assert.equal(classified.causeCategoryCode,'X');
  assert.equal(classified.causeSubtype,'FORESTACIÓN / REFORESTACIÓN');
});
