import express from 'express';
import cors from 'cors';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { authRouter } from './modules/auth.js';
import { catalogsRouter } from './modules/catalogs.js';
import { dashboardRouter } from './modules/dashboard.js';
import { adminRouter } from './modules/admin.js';
import { trainingsRouter } from './modules/trainings.js';
import { racsRouter } from './modules/racs.js';
import { environmentRouter } from './modules/environment.js';
import { ssomaRouter } from './modules/ssoma.js';
import { incidentsRouter } from './modules/incidents.js';
import { reportsRouter } from './modules/reports.js';
import { publicRouter } from './modules/public.js';
import { notificationsRouter } from './modules/notifications.js';
import { filesRouter } from './modules/files.js';
import { notFound, errorHandler } from './middleware/error.js';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
export const app=express();
app.disable('x-powered-by');
app.use(cors({origin:true,credentials:false}));
app.use(express.json({limit:'5mb'}));
app.use(express.urlencoded({extended:true,limit:'5mb'}));
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','SAMEORIGIN');res.setHeader('Referrer-Policy','same-origin');next();});
app.get('/api/health',(_req,res)=>res.json({ok:true,version:'4.0.18',system:'CAPSAN6 Gestión SSOMA'}));
app.get('/api/version',(_req,res)=>res.json({version:'4.0.18-PLANES-Y-EVIDENCIAS-SSOMA-COMPLETOS-4.0.17-PPT-EJECUTIVO-RACS-ONLY-GERENCIA-4.0.16-HOTFIX-DEPURACION-RACS-SIN-RECARGA-4.0.15-ASIGNACION-AUTOMATICA-TODOS-SUPERVISORES-POR-UNIDAD-ALCANCE-SUPERVISOR-REPARADO-HOTFIX-REGISTRO-RAC-SIN-ERROR-RESET'}));
app.use('/api/auth',authRouter);
app.use('/api/catalogs',catalogsRouter);
app.use('/api/dashboard',dashboardRouter);
app.use('/api/admin',adminRouter);
app.use('/api/trainings',trainingsRouter);
app.use('/api/racs',racsRouter);
app.use('/api/environment',environmentRouter);
app.use('/api/ssoma',ssomaRouter);
app.use('/api/incidents',incidentsRouter);
app.use('/api/reports',reportsRouter);
app.use('/api/public',publicRouter);
app.use('/api/notifications',notificationsRouter);
app.use('/api/files',filesRouter);
app.use(express.static(path.resolve(__dirname,'../public'),{etag:true,maxAge:'5m'}));
app.get('*',(req,res,next)=>req.path.startsWith('/api/')?next():res.sendFile(path.resolve(__dirname,'../public/index.html')));
app.use(notFound);
app.use(errorHandler);
