export const RAC_CAUSE_CATALOG = Object.freeze([
  { code:'I', name:'GEOMECÁNICA Y TERRENO', reportType:'CONDICION SUBESTANDAR', subtypes:[
    'ROCAS SUELTAS / FALTA DE SOSTENIMIENTO','PAREDES, TECHOS O HASTIALES INESTABLES','FALLAS EN INSPECCIÓN GEOMECÁNICA','SOSTENIMIENTO INADECUADO O INEXISTENTE','CAÍDA DE ROCAS POR VIBRACIÓN, VOLADURA O TRÁNSITO DE EQUIPOS'
  ]},
  { code:'II', name:'OPERACIONES MINA', reportType:'CONDICION SUBESTANDAR', subtypes:[
    'CHIMENEA O REALCE EN MAL ESTADO','MANEJO DE EXPLOSIVOS, TIROS FALLADOS, CORTADOS O NO DETONADOS','DISPAROS FUERA DE HORARIO','ILUMINACIÓN DEFICIENTE','MANIPULACIÓN DE MINERAL O DESMONTE','CAMPANEO DE TOLVAS','IZAJE DE MATERIALES','DEFICIENCIA DE RELLENO','PERFORACIÓN FUERA DE ESTÁNDAR','VOLADURA FUERA DE ESTÁNDAR'
  ]},
  { code:'III', name:'TRANSPORTE Y TRÁNSITO (CRÍTICO)', reportType:'CONDICION SUBESTANDAR', subtypes:[
    'ACARREO Y TRANSPORTE DE DESMONTE O MINERAL','VÍAS, CAMINOS O ACCESOS EN MAL ESTADO','INTERFERENCIA EN VÍAS, CRUCES, OBSTRUCCIONES O EQUIPOS ESTACIONADOS','OPERACIÓN A VELOCIDAD INADECUADA','FALTA O USO INADECUADO DE SEÑALIZACIÓN EN EQUIPOS MÓVILES','FALTA DE CONTROL DE TRÁNSITO INTERNO','POSICIONAMIENTO INCORRECTO DE EQUIPOS','TRÁNSITO INTERNO INSEGURO'
  ]},
  { code:'IV', name:'EQUIPOS, HERRAMIENTAS Y ENERGÍA', reportType:'CONDICION SUBESTANDAR', subtypes:[
    'EQUIPOS O MAQUINARIA EN MAL ESTADO','HERRAMIENTAS DEFECTUOSAS','MANTENIMIENTO MECÁNICO O ELÉCTRICO DEFICIENTE','ENERGÍA ELÉCTRICA INCONTROLADA','FALTA DE BLOQUEO Y ROTULADO (LOTO)','INSTALACIONES DE AIRE O AGUA DEFECTUOSAS','BOMBAS O TUBERÍAS','EQUIPOS DE SECADO DEFICIENTES O ESTUFAS','EQUIPOS SIN GUARDA DE SEGURIDAD','FALTA DE DISPOSITIVOS DE SEGURIDAD','FALTA DE HERRAMIENTAS O MATERIALES','EPP EN MAL ESTADO O FALTA DE EPP'
  ]},
  { code:'V', name:'CONDICIONES DE TRABAJO', reportType:'CONDICION SUBESTANDAR', subtypes:[
    'PISOS, ESPACIOS ABIERTOS O DESNIVEL','PELDAÑO SUELTO','PELDAÑO ROTO','ESCALERA EN MAL ESTADO','ORDEN Y LIMPIEZA DEFICIENTE','ILUMINACIÓN DEFICIENTE O EXCESIVA','DEFICIENCIA DE VENTILACIÓN','TEMPERATURAS EXTREMAS','CONGESTIÓN O RESTRICCIÓN DE ESPACIO','FALTA DE SEÑALIZACIÓN','FALTA DE BARANDAS, BERMAS O BARRERAS','EXPOSICIÓN AL RUIDO','INFRAESTRUCTURA O INSTALACIONES DEFICIENTES','PLAGAS'
  ]},
  { code:'VI', name:'MEDIO AMBIENTE Y SUSTANCIAS PELIGROSAS', reportType:'CONDICION SUBESTANDAR', subtypes:[
    'GENERACIÓN DE POLVO EXCESIVO','EMISIÓN DE GASES SOBRE LMP','MANEJO DE SUSTANCIAS PELIGROSAS','MANEJO INADECUADO DE HIDROCARBUROS','MANEJO DE RESIDUOS PELIGROSOS O NO PELIGROSOS','MANEJO DE RELAVES','MANEJO DE LODOS DE PERFORACIÓN','SOLUCIÓN ALUMINADA','PELIGRO DE INCENDIO O EXPLOSIÓN'
  ]},
  { code:'VII', name:'FACTORES HUMANOS (ACTOS SUBESTÁNDAR)', reportType:'ACTO SUBESTANDAR', subtypes:[
    'INCUMPLIMIENTO DE PROCEDIMIENTOS','EXCESO DE CONFIANZA','DISTRACCIÓN O FALTA DE ATENCIÓN','USO INCORRECTO DE HERRAMIENTAS Y EQUIPOS','NO USO DE EPP','FATIGA FÍSICA O MENTAL','POSICIONAMIENTO INCORRECTO FRENTE AL PELIGRO','FALTA FÍSICA O MENTAL','ACTO INSEGURO DELIBERADO'
  ]},
  { code:'VIII', name:'HABITABILIDAD, ALIMENTACIÓN Y SERVICIOS DE CAMPAMENTO', reportType:'CONDICION SUBESTANDAR', subtypes:[
    'NO HAY AGUA CALIENTE','FUGA DE AGUA','HUMEDAD EN PAREDES','SSHH EN MAL ESTADO','CAMAS EN MAL ESTADO','POCA CANTIDAD DE COMIDA','VASOS O TÁPERES CON OLOR A DETERGENTE','CUBIERTOS PLÁSTICOS INADECUADOS','ENVÍO DE ALIMENTOS EN BOLSAS O RECIPIENTES INADECUADOS','CORTE DE ENERGÍA ELÉCTRICA','FALTA DE SEÑAL WIFI','DEFICIENCIA O FALTA DE AGUA','DEFICIENCIA DE VESTUARIOS','CAMPAMENTOS EN MAL ESTADO'
  ]},
  { code:'IX', name:'LOGÍSTICA, STOCK Y ABASTECIMIENTO', reportType:'CONDICION SUBESTANDAR', subtypes:[
    'FALLA EN LA PROGRAMACIÓN DE STOCK'
  ]},
  { code:'X', name:'ASPECTOS AMBIENTALES', reportType:'CONDICION SUBESTANDAR', subtypes:[
    'CONSUMO DE AGUA',
    'CONSUMO DE ENERGÍA ELÉCTRICA',
    'CONSUMO DE HIDROCARBUROS',
    'CONSUMO DE MADERA',
    'CONSUMO DE PAPEL',
    'CONSUMO DE AIRE COMPRIMIDO',
    'GENERACIÓN DE AGUAS ÁCIDAS O CONTAMINADAS',
    'DERRAME DE SUSTANCIAS PELIGROSAS (QUÍMICOS E HIDROCARBUROS)',
    'GENERACIÓN Y DISPOSICIÓN DE DESMONTE, LODOS Y LAMAS',
    'GENERACIÓN Y DISPOSICIÓN DE RESIDUOS',
    'DISPOSICIÓN DE MINERAL',
    'DERRAME DE RELAVES O SOLUCIONES CIANURADAS',
    'EMISIÓN DE RUIDO',
    'EMISIÓN DE VIBRACIÓN',
    'EMISIÓN DE POLVO Y/O PARTÍCULAS',
    'EMISIÓN DE CALOR',
    'EMISIÓN DE RADIACIÓN',
    'EMISIÓN DE GASES, VAPORES Y/O HUMOS',
    'EXTRACCIÓN DE MINERAL',
    'FUGA DE AGUA Y DESAGÜE',
    'FUGA DE GLP',
    'GENERACIÓN Y DISPOSICIÓN FINAL DE HIDROCARBUROS USADOS Y EN DESUSO',
    'POTENCIAL EMISIÓN DE GASES TÓXICOS',
    'POTENCIAL COLAPSO DE PRESA DE RELAVES',
    'POTENCIAL DERRAME DE AGUA DE LA PRESA DE RELAVES, PULPA O SOLUCIÓN CIANURADA',
    'POTENCIAL DERRAME DE SUSTANCIAS QUÍMICAS Y/O PELIGROSAS',
    'POTENCIAL DERRAME DE HIDROCARBUROS EN USO, DESUSO Y USADOS',
    'POTENCIAL DERRAME DE ACEITES DIELÉCTRICOS',
    'POTENCIAL DERRAME DE CONCENTRADOS',
    'POTENCIAL DERRAME DE LODOS Y/O LAMAS',
    'POTENCIAL DERRAME DE MINERAL',
    'POTENCIAL DERRAME DE RELAVES',
    'POTENCIAL DERRAME DE EFLUENTES LÍQUIDOS CON PARÁMETROS QUE EXCEDEN LOS LMP',
    'POTENCIAL DERRAME DE CAL',
    'POTENCIAL EROSIÓN',
    'REMOCIÓN DE SUELOS',
    'POTENCIAL INCENDIO',
    'POTENCIAL DERRUMBE',
    'POTENCIAL FALLA DE INSTALACIONES E INFRAESTRUCTURA',
    'POTENCIAL INUNDACIÓN',
    'POTENCIAL DERRAME DE RESIDUOS SÓLIDOS DURANTE SU DISPOSICIÓN',
    'POTENCIAL FALLA DE CIERRE DE COMPONENTES',
    'POTENCIAL FALLA DE ESTRUCTURAS HIDRÁULICAS',
    'POTENCIAL FALTA DE GERMINACIÓN',
    'POTENCIAL GENERACIÓN DE LIXIVIADOS',
    'POTENCIAL HUNDIMIENTO',
    'POTENCIAL ROTURA DE GEOMEMBRANA DE LA PRESA DE RELAVES',
    'FORESTACIÓN / REFORESTACIÓN',
    'PLANES DE CIERRE'
  ]}
]);



const SOURCE_CAUSE_ALIASES = Object.freeze({
  'ACTO INSEGURO DELIBERADO':['VII','ACTO INSEGURO DELIBERADO'],
  'ALIMENTOS':['VIII','POCA CANTIDAD DE COMIDA'],
  'DEFICIENCIA COMIDA':['VIII','POCA CANTIDAD DE COMIDA'],
  'BARANDA CERCO BARRERA BERMA INADECUADO':['V','FALTA DE BARANDAS, BERMAS O BARRERAS'],
  'CABLES ELECTRICOS':['IV','ENERGÍA ELÉCTRICA INCONTROLADA'],
  'ENERGIA ELECTRICA':['IV','ENERGÍA ELÉCTRICA INCONTROLADA'],
  'CAMINOS ACCESOS EN MAL ESTADO':['III','VÍAS, CAMINOS O ACCESOS EN MAL ESTADO'],
  'CAMINOS ACCESOS INADECUADOS':['III','VÍAS, CAMINOS O ACCESOS EN MAL ESTADO'],
  'VIAS EN MAL ESTADO':['III','VÍAS, CAMINOS O ACCESOS EN MAL ESTADO'],
  'CAMPAMENTOS':['VIII','CAMPAMENTOS EN MAL ESTADO'],
  'CONGESTION O RESTRICCION DE ESPACIO':['V','CONGESTIÓN O RESTRICCIÓN DE ESPACIO'],
  'CONGESTION O RESTRICCION DEL PASO':['V','CONGESTIÓN O RESTRICCIÓN DE ESPACIO'],
  'FUERA DE ESTANDAR ESPACIO REDUCIDO':['V','CONGESTIÓN O RESTRICCIÓN DE ESPACIO'],
  'DEF VESTUARIOS':['VIII','DEFICIENCIA DE VESTUARIOS'],
  'DEFICIENCIA AIRE':['V','DEFICIENCIA DE VENTILACIÓN'],
  'DEFICIENCIA DE VENTILACION':['V','DEFICIENCIA DE VENTILACIÓN'],
  'DEFICIENCIA O FALTA DE VENTILACION':['V','DEFICIENCIA DE VENTILACIÓN'],
  'VENTILACION DEFICIENTE':['V','DEFICIENCIA DE VENTILACIÓN'],
  'DEFICIENCIA INTERNET':['VIII','FALTA DE SEÑAL WIFI'],
  'DEFICIENCIA O FALTA DE AGUA':['VIII','DEFICIENCIA O FALTA DE AGUA'],
  'DEFICIENCIA RELLENO':['II','DEFICIENCIA DE RELLENO'],
  'DEFICIENTE O FALTA ILUMINACION':['V','ILUMINACIÓN DEFICIENTE O EXCESIVA'],
  'FALTA DE ILUMINACION':['V','ILUMINACIÓN DEFICIENTE O EXCESIVA'],
  'ILUMINACION DEFICIENTE O EXCESIVA':['V','ILUMINACIÓN DEFICIENTE O EXCESIVA'],
  'DISTRACCION O FALTA DE ATENCION':['VII','DISTRACCIÓN O FALTA DE ATENCIÓN'],
  'EPPS EN MAL ESTADO':['IV','EPP EN MAL ESTADO O FALTA DE EPP'],
  'EPPS EN MAL ESTADO O FALTA DE EPPS':['IV','EPP EN MAL ESTADO O FALTA DE EPP'],
  'FALTA DE EPPS':['IV','EPP EN MAL ESTADO O FALTA DE EPP'],
  'EQUIPO MAQUINARIA EN MAL ESTADO':['IV','EQUIPOS O MAQUINARIA EN MAL ESTADO'],
  'EQUIPOS MAQUINARIA EN MAL ESTADO':['IV','EQUIPOS O MAQUINARIA EN MAL ESTADO'],
  'EQUIPOS O MAQUINARIA EN MAL ESTADO':['IV','EQUIPOS O MAQUINARIA EN MAL ESTADO'],
  'MAL ESTADO DE EQUIPOS MAQUINARIAS':['IV','EQUIPOS O MAQUINARIA EN MAL ESTADO'],
  'EQUIPOS SIN GUARDA DE SEGURIDAD':['IV','EQUIPOS SIN GUARDA DE SEGURIDAD'],
  'ESPACIO ABIERTO':['V','PISOS, ESPACIOS ABIERTOS O DESNIVEL'],
  'ESPACIOS ABIERTOS':['V','PISOS, ESPACIOS ABIERTOS O DESNIVEL'],
  'EXPLOSIVOS':['II','MANEJO DE EXPLOSIVOS, TIROS FALLADOS, CORTADOS O NO DETONADOS'],
  'TIROS CORTADOS':['II','MANEJO DE EXPLOSIVOS, TIROS FALLADOS, CORTADOS O NO DETONADOS'],
  'EXPOSICION AL RUIDO':['V','EXPOSICIÓN AL RUIDO'],
  'RUIDO':['V','EXPOSICIÓN AL RUIDO'],
  'FALTA DE BARANDAS BERMAS O BARRERAS':['V','FALTA DE BARANDAS, BERMAS O BARRERAS'],
  'FALTA DE DISPOSITIVOS DE SEGURIDAD':['IV','FALTA DE DISPOSITIVOS DE SEGURIDAD'],
  'FALTA DE IMPLEMENTOS DE SEGURIDAD':['IV','FALTA DE DISPOSITIVOS DE SEGURIDAD'],
  'NO UTILIZAR DISPOSITIVOS DE SEGURIDAD':['VII','INCUMPLIMIENTO DE PROCEDIMIENTOS'],
  'FALTA DE HERRAMIENTAS':['IV','FALTA DE HERRAMIENTAS O MATERIALES'],
  'FALTA DE HERRAMIENTAS MATERIALES':['IV','FALTA DE HERRAMIENTAS O MATERIALES'],
  'FALTA DE ORDEN Y LIMPIEZA':['V','ORDEN Y LIMPIEZA DEFICIENTE'],
  'FALTA ORDEN Y LIMPIEZA':['V','ORDEN Y LIMPIEZA DEFICIENTE'],
  'ORDEN Y LIMPIEZA DEFICIENTE':['V','ORDEN Y LIMPIEZA DEFICIENTE'],
  'FALTA DE SENALIZACION':['V','FALTA DE SEÑALIZACIÓN'],
  'SENALIZACION':['V','FALTA DE SEÑALIZACIÓN'],
  'FALTA DE SOSTENIMIENTO':['I','ROCAS SUELTAS / FALTA DE SOSTENIMIENTO'],
  'ROCA SUELTA':['I','ROCAS SUELTAS / FALTA DE SOSTENIMIENTO'],
  'ROCAS SUELTAS':['I','ROCAS SUELTAS / FALTA DE SOSTENIMIENTO'],
  'HERRAMIENTAS DEFECTUOSAS':['IV','HERRAMIENTAS DEFECTUOSAS'],
  'MAL ESTADO DE HERRAMIENTAS':['IV','HERRAMIENTAS DEFECTUOSAS'],
  'MAL ESTADO DE HERRAMIENTAS MATERIALES':['IV','HERRAMIENTAS DEFECTUOSAS'],
  'HORARIO DE DISPARO':['II','DISPAROS FUERA DE HORARIO'],
  'INFRAESTRUCTURA':['V','INFRAESTRUCTURA O INSTALACIONES DEFICIENTES'],
  'INSTALACIONES':['V','INFRAESTRUCTURA O INSTALACIONES DEFICIENTES'],
  'INSTALACION DE AIRE AGUA DEFECTUOSA':['IV','INSTALACIONES DE AIRE O AGUA DEFECTUOSAS'],
  'INTERFERENCIA EN VIAS':['III','INTERFERENCIA EN VÍAS, CRUCES, OBSTRUCCIONES O EQUIPOS ESTACIONADOS'],
  'INTERFERENCIA EN VIAS CRUCES EQUIPOS MAL ESTACIONADOS':['III','INTERFERENCIA EN VÍAS, CRUCES, OBSTRUCCIONES O EQUIPOS ESTACIONADOS'],
  'MANEJO DE RELAVES':['VI','MANEJO DE RELAVES'],
  'MANEJO DE RESIDUOS PELIGROSOS NO PELIGROSOS':['VI','MANEJO DE RESIDUOS PELIGROSOS O NO PELIGROSOS'],
  'MANEJO INADECUADO DE HIDROCARBUROS':['VI','MANEJO INADECUADO DE HIDROCARBUROS'],
  'NO USO DE EPPS':['VII','NO USO DE EPP'],
  'NO UTILIZAR EPPS':['VII','NO USO DE EPP'],
  'PERFORACION':['II','PERFORACIÓN FUERA DE ESTÁNDAR'],
  'PLAGAS':['V','PLAGAS'],
  'TRANSITO':['III','TRÁNSITO INTERNO INSEGURO'],
  'VOLADURA':['II','VOLADURA FUERA DE ESTÁNDAR']
});

export const normalizeCauseText = value => String(value || '')
  .normalize('NFD').replace(/[\u0300-\u036f]/g,'')
  .toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim().replace(/\s+/g,' ');

export function categoryByReference(value, reportType='') {
  const key=normalizeCauseText(value);const type=normalizeCauseText(reportType);
  return RAC_CAUSE_CATALOG.find(category=>(!type||normalizeCauseText(category.reportType)===type)&&[category.code,category.name].some(item=>normalizeCauseText(item)===key))||null;
}

export function subtypeByReference(value, category=null) {
  const key=normalizeCauseText(value);if(!key)return null;
  const categories=category?[category]:RAC_CAUSE_CATALOG;
  for(const item of categories){const name=item.subtypes.find(subtype=>normalizeCauseText(subtype)===key);if(name)return{category:item,name};}
  return null;
}

const RULES = [
  { words:['ROCA SUELTA','SOSTENIMIENTO','HASTIAL','TECHO INESTABLE','CUADRO DE MADERA'], code:'I', subtype:'ROCAS SUELTAS / FALTA DE SOSTENIMIENTO' },
  { words:['CHIMENEA','REALCE'], code:'II', subtype:'CHIMENEA O REALCE EN MAL ESTADO' },
  { words:['EXPLOSIVO','TIRO FALLADO','TIRO CORTADO','NO DETONADO'], code:'II', subtype:'MANEJO DE EXPLOSIVOS, TIROS FALLADOS, CORTADOS O NO DETONADOS' },
  { words:['ACARREO','TRANSPORTE DE MINERAL','TRANSPORTE DE DESMONTE'], code:'III', subtype:'ACARREO Y TRANSPORTE DE DESMONTE O MINERAL' },
  { words:['VIA EN MAL ESTADO','CAMINO EN MAL ESTADO','ACCESO INADECUADO'], code:'III', subtype:'VÍAS, CAMINOS O ACCESOS EN MAL ESTADO' },
  { words:['OBSTRUCCION','INTERFERENCIA EN VIA','CRUCE BLOQUEADO','EQUIPO ESTACIONADO'], code:'III', subtype:'INTERFERENCIA EN VÍAS, CRUCES, OBSTRUCCIONES O EQUIPOS ESTACIONADOS' },
  { words:['EXCESO DE VELOCIDAD','VELOCIDAD INADECUADA'], code:'III', subtype:'OPERACIÓN A VELOCIDAD INADECUADA' },
  { words:['EQUIPO EN MAL ESTADO','MAQUINA EN MAL ESTADO','MAQUINARIA EN MAL ESTADO','FALLA DE EQUIPO','CELDA','LOCOMOTORA'], code:'IV', subtype:'EQUIPOS O MAQUINARIA EN MAL ESTADO' },
  { words:['HERRAMIENTA DEFECTUOSA','HERRAMIENTA EN MAL ESTADO'], code:'IV', subtype:'HERRAMIENTAS DEFECTUOSAS' },
  { words:['CABLE ELECTRICO','ENERGIA ELECTRICA','TABLERO ELECTRICO','PULSADOR'], code:'IV', subtype:'ENERGÍA ELÉCTRICA INCONTROLADA' },
  { words:['LOTO','BLOQUEO Y ROTULADO','FALTA DE BLOQUEO'], code:'IV', subtype:'FALTA DE BLOQUEO Y ROTULADO (LOTO)' },
  { words:['BOMBA','TUBERIA'], code:'IV', subtype:'BOMBAS O TUBERÍAS' },
  { words:['DESORDEN','BASURA','SUCIO','LIMPIEZA DEFICIENTE','FALTA DE ORDEN'], code:'V', subtype:'ORDEN Y LIMPIEZA DEFICIENTE' },
  { words:['VENTILACION','MONOXIDO','GAS','HUMO','AIRE VICIADO'], code:'V', subtype:'DEFICIENCIA DE VENTILACIÓN' },
  { words:['ILUMINACION'], code:'V', subtype:'ILUMINACIÓN DEFICIENTE O EXCESIVA' },
  { words:['FALTA DE SEÑALIZACION','SIN SEÑALIZACION'], code:'V', subtype:'FALTA DE SEÑALIZACIÓN' },
  { words:['BARANDA','BERMA','BARRERA'], code:'V', subtype:'FALTA DE BARANDAS, BERMAS O BARRERAS' },
  { words:['POLVO','POLVADERA'], code:'VI', subtype:'GENERACIÓN DE POLVO EXCESIVO' },
  { words:['EMISION DE GAS','GASES SOBRE LMP'], code:'VI', subtype:'EMISIÓN DE GASES SOBRE LMP' },
  { words:['HIDROCARBURO','DERRAME DE ACEITE','DERRAME DE COMBUSTIBLE'], code:'VI', subtype:'MANEJO INADECUADO DE HIDROCARBUROS' },
  { words:['RESIDUO PELIGROSO','RESIDUO NO PELIGROSO','SEGREGACION DE RESIDUOS'], code:'VI', subtype:'MANEJO DE RESIDUOS PELIGROSOS O NO PELIGROSOS' },
  { words:['RELAVE'], code:'VI', subtype:'MANEJO DE RELAVES' },
  { words:['LODO DE PERFORACION'], code:'VI', subtype:'MANEJO DE LODOS DE PERFORACIÓN' },
  { words:['INCENDIO','EXPLOSION'], code:'VI', subtype:'PELIGRO DE INCENDIO O EXPLOSIÓN' },
  { words:['NO USA EPP','SIN EPP','NO USO DE EPP','SIN GUANTE','SIN CASCO','SIN LENTE','SIN ARNES'], code:'VII', subtype:'NO USO DE EPP' },
  { words:['PROCEDIMIENTO','IPERC','PETAR','SIN AUTORIZACION'], code:'VII', subtype:'INCUMPLIMIENTO DE PROCEDIMIENTOS' },
  { words:['DISTRACCION','FALTA DE ATENCION'], code:'VII', subtype:'DISTRACCIÓN O FALTA DE ATENCIÓN' },
  { words:['EXCESO DE CONFIANZA'], code:'VII', subtype:'EXCESO DE CONFIANZA' },
  { words:['FATIGA','CANSANCIO'], code:'VII', subtype:'FATIGA FÍSICA O MENTAL' },
  { words:['ACTO INSEGURO'], code:'VII', subtype:'ACTO INSEGURO DELIBERADO' },
  { words:['AGUA CALIENTE'], code:'VIII', subtype:'NO HAY AGUA CALIENTE' },
  { words:['FUGA DE AGUA'], code:'VIII', subtype:'FUGA DE AGUA' },
  { words:['COMIDA','ALIMENTO','RACION'], code:'VIII', subtype:'POCA CANTIDAD DE COMIDA' },
  { words:['CAMA','COLCHON'], code:'VIII', subtype:'CAMAS EN MAL ESTADO' },
  { words:['WIFI','INTERNET'], code:'VIII', subtype:'FALTA DE SEÑAL WIFI' },
  { words:['PROGRAMACION DE STOCK','FALLA DE STOCK','FALTA DE STOCK','NO HAY STOCK','SIN STOCK','DESABASTECIMIENTO','QUIEBRE DE STOCK'], code:'IX', subtype:'FALLA EN LA PROGRAMACIÓN DE STOCK' }
];

export function classifyCauseFromCatalog(text, preferredReportType='') {
  const normalized=normalizeCauseText(text);
  const direct=SOURCE_CAUSE_ALIASES[normalized];
  if(direct){const category=RAC_CAUSE_CATALOG.find(item=>item.code===direct[0]);return{reportType:category.reportType,causeCategoryCode:category.code,causeCategory:category.name,causeSubtype:direct[1],score:100};}
  const exact=subtypeByReference(text);
  if(exact)return{reportType:exact.category.reportType,causeCategoryCode:exact.category.code,causeCategory:exact.category.name,causeSubtype:exact.name,score:100};
  let best=null;
  for(const rule of RULES){const score=rule.words.reduce((total,word)=>total+(normalized.includes(normalizeCauseText(word))?1:0),0);if(score&&(!best||score>best.score))best={...rule,score};}
  if(!best){const act=normalizeCauseText(preferredReportType)==='ACTO SUBESTANDAR'||/TRABAJADOR|PERSONAL|OPERADOR/.test(normalized);best=act?{code:'VII',subtype:'ACTO INSEGURO DELIBERADO',score:0}:{code:'V',subtype:'ORDEN Y LIMPIEZA DEFICIENTE',score:0};}
  const category=RAC_CAUSE_CATALOG.find(item=>item.code===best.code);return{reportType:category.reportType,causeCategoryCode:category.code,causeCategory:category.name,causeSubtype:best.subtype,score:best.score};
}

export const flattenedCauseCatalog = () => RAC_CAUSE_CATALOG.flatMap((category,categoryIndex)=>category.subtypes.map((name,subtypeIndex)=>({categoryCode:category.code,categoryName:category.name,reportType:category.reportType,categoryOrder:categoryIndex+1,name,subtypeOrder:subtypeIndex+1})));
