import ExcelJS from 'exceljs';
import pptxgen from 'pptxgenjs';

const C={navy:'17324D',teal:'1B7F79',mint:'A7D7C5',amber:'F2B134',coral:'E76F51',cream:'F7F2E8',ink:'203040',white:'FFFFFF',gray:'D9E1E8',green:'4E9F6F',red:'C84C4C'};
const pct=(a,b)=>Number(b)?Math.round(Number(a)*100/Number(b)):0;
const text=v=>String(v??'').trim();

export function summarizeRacs(rows=[],workerCounts={}){
  const summary={total:rows.length,acts:0,conditions:0,lifted:0,pending:0,high:0};const units=new Map();
  for(const r of rows){const unit=text(r.business_unit)||'SIN UNIDAD';if(!units.has(unit))units.set(unit,{name:unit,total:0,acts:0,conditions:0,lifted:0,pending:0,high:0,risks:{ALTO:0,MEDIO:0,BAJO:0},supervisors:new Map(),areas:new Map(),causes:new Map(),rows:[]});const u=units.get(unit);u.rows.push(r);u.total++;summary.total=rows.length;
    if(r.report_type==='ACTO SUBESTANDAR'){u.acts++;summary.acts++;}else{u.conditions++;summary.conditions++;}if(r.status==='LEVANTADO'){u.lifted++;summary.lifted++;}else{u.pending++;summary.pending++;}if(r.risk_level==='ALTO'){u.high++;summary.high++;}u.risks[r.risk_level]=(u.risks[r.risk_level]||0)+1;
    const s=text(r.supervisor_name)||'SIN ASIGNAR';u.supervisors.set(s,(u.supervisors.get(s)||0)+1);const a=text(r.reporting_area)||'SIN ÁREA';u.areas.set(a,(u.areas.get(a)||0)+1);const c=text(r.cause_subtype||r.deviation_type)||'OTROS';u.causes.set(c,(u.causes.get(c)||0)+1);
  }
  summary.closurePercent=pct(summary.lifted,summary.total);
  return {summary,units:[...units.values()].map(u=>({...u,workers:Number(workerCounts[u.name]||0),reportRate:Number(workerCounts[u.name]||0)?Number((u.total/Number(workerCounts[u.name])).toFixed(2)):0,closurePercent:pct(u.lifted,u.total),supervisors:[...u.supervisors.entries()].map(([name,total])=>({name,total})).sort((a,b)=>b.total-a.total),areas:[...u.areas.entries()].map(([name,total])=>({name,total})).sort((a,b)=>b.total-a.total),causes:[...u.causes.entries()].map(([name,total])=>({name,total})).sort((a,b)=>b.total-a.total)})).sort((a,b)=>b.total-a.total)};
}

function addTitle(slide,title,subtitle=''){
  slide.background={color:C.cream};slide.addShape('rect',{x:0,y:0,w:13.333,h:0.72,fill:{color:C.navy},line:{color:C.navy}});slide.addText(title,{x:0.45,y:0.18,w:8.7,h:0.3,fontFace:'Aptos Display',fontSize:23,bold:true,color:C.white,margin:0});if(subtitle)slide.addText(subtitle,{x:9.1,y:0.22,w:3.7,h:0.25,fontSize:9,color:C.mint,align:'right',margin:0});
}
function card(slide,x,y,w,title,value,color=C.teal,note=''){
  slide.addShape('roundRect',{x,y,w,h:1.08,rectRadius:0.06,fill:{color:C.white},line:{color:C.gray,width:1}});slide.addShape('rect',{x,y,w:0.12,h:1.08,fill:{color},line:{color}});slide.addText(title,{x:x+0.24,y:y+0.16,w:w-0.35,h:0.22,fontSize:10,bold:true,color:C.ink,margin:0});slide.addText(String(value),{x:x+0.24,y:y+0.43,w:w-0.35,h:0.36,fontSize:22,bold:true,color,margin:0});if(note)slide.addText(note,{x:x+0.24,y:y+0.84,w:w-0.35,h:0.14,fontSize:7.5,color:'64748B',margin:0});
}
function footer(slide){slide.addText('CAPSAN6 · SISTEMA DE GESTIÓN SSOMA',{x:0.45,y:7.22,w:6,h:0.15,fontSize:7,color:'708090',margin:0});}
function chartData(items,limit=8){return items.slice(0,limit).map(x=>({name:x.name,label:x.name,total:Number(x.total)}));}

export async function buildRacExecutivePpt(rows,filtersLabel,workerCounts={}){
  const data=summarizeRacs(rows,workerCounts);const pptx=new pptxgen();pptx.layout='LAYOUT_WIDE';pptx.author='CAPSAN6';pptx.subject='Reporte Ejecutivo SSOMA';pptx.title='Reporte Diario de Seguridad';pptx.company='CAPSAN6';pptx.lang='es-PE';pptx.theme={headFontFace:'Aptos Display',bodyFontFace:'Aptos'};
  let slide=pptx.addSlide();slide.background={color:C.navy};slide.addShape('rect',{x:0,y:5.45,w:13.333,h:2.05,fill:{color:C.teal},line:{color:C.teal}});slide.addText('SEGURIDAD Y SALUD OCUPACIONAL',{x:0.75,y:1.25,w:11.8,h:0.55,fontSize:32,bold:true,color:C.white,align:'center',margin:0});slide.addText('REPORTE EJECUTIVO SSOMA',{x:0.75,y:2.0,w:11.8,h:0.65,fontSize:42,bold:true,color:C.amber,align:'center',margin:0});slide.addText(filtersLabel,{x:1.2,y:3.0,w:10.9,h:0.35,fontSize:16,color:C.mint,align:'center',margin:0});slide.addText(new Date().toLocaleString('es-PE'),{x:0.75,y:6.28,w:11.8,h:0.25,fontSize:12,color:C.white,align:'center',margin:0});
  slide=pptx.addSlide();addTitle(slide,'RESUMEN EJECUTIVO GENERAL',filtersLabel);card(slide,0.55,1.05,2.15,'TOTAL RACS',data.summary.total,C.navy);card(slide,2.9,1.05,2.15,'ACTOS',data.summary.acts,C.coral);card(slide,5.25,1.05,2.15,'CONDICIONES',data.summary.conditions,C.teal);card(slide,7.6,1.05,2.15,'ALTO POTENCIAL',data.summary.high,C.red);card(slide,9.95,1.05,2.15,'% LEVANTAMIENTO',`${data.summary.closurePercent}%`,C.green);
  const unitItems=data.units.map(x=>({name:x.name,total:x.total}));if(unitItems.length)slide.addChart(pptx.ChartType.bar,[{name:'RACS',labels:unitItems.map(x=>x.name),values:unitItems.map(x=>x.total)}],{x:0.7,y:2.55,w:6.0,h:3.9,catAxisLabelFontSize:9,valAxisLabelFontSize:9,showLegend:false,showTitle:true,title:'RACS por unidad de negocio',chartColors:[C.teal],showValue:true,showCatName:false,showValAxisTitle:false,showCatAxisTitle:false});
  slide.addChart(pptx.ChartType.doughnut,[{name:'Estado',labels:['Levantados','Pendientes'],values:[data.summary.lifted,data.summary.pending]}],{x:7.2,y:2.55,w:5.0,h:3.9,showLegend:true,legendPos:'b',showTitle:true,title:'Estado de levantamiento',chartColors:[C.green,C.amber],showPercent:true,holeSize:58});footer(slide);
  for(const u of data.units){
    slide=pptx.addSlide();addTitle(slide,`RACS ${u.name}`,filtersLabel);card(slide,0.55,1.0,2.05,'PERSONAL',u.workers,C.navy);card(slide,2.75,1.0,2.05,'RACS',u.total,C.teal);card(slide,4.95,1.0,2.05,'RACS/TRABAJADOR',u.reportRate,C.amber);card(slide,7.15,1.0,2.05,'ALTO POTENCIAL',u.high,C.red);card(slide,9.35,1.0,2.05,'% LEVANTAMIENTO',`${u.closurePercent}%`,C.green);
    slide.addText(`Se registraron ${u.total} reportes RACS (${u.acts} actos y ${u.conditions} condiciones). ${u.high} fueron de alto potencial.`,{x:0.7,y:2.35,w:11.8,h:0.45,fontSize:16,bold:true,color:C.ink,align:'center',margin:0.05});
    slide.addChart(pptx.ChartType.column,[{name:'RACS',labels:u.supervisors.slice(0,8).map(x=>x.name),values:u.supervisors.slice(0,8).map(x=>x.total)}],{x:0.65,y:3.05,w:5.9,h:3.45,showTitle:true,title:'Supervisores que entregaron RACS',showLegend:false,chartColors:[C.coral],showValue:true,catAxisLabelRotate:-25,catAxisLabelFontSize:8,valAxisLabelFontSize:8});
    slide.addChart(pptx.ChartType.column,[{name:'RACS',labels:u.areas.slice(0,8).map(x=>x.name),values:u.areas.slice(0,8).map(x=>x.total)}],{x:6.8,y:3.05,w:5.9,h:3.45,showTitle:true,title:'Áreas reportantes',showLegend:false,chartColors:[C.teal],showValue:true,catAxisLabelRotate:-25,catAxisLabelFontSize:8,valAxisLabelFontSize:8});footer(slide);
    slide=pptx.addSlide();addTitle(slide,`ANÁLISIS DE RIESGO Y CAUSAS · ${u.name}`,filtersLabel);
    slide.addChart(pptx.ChartType.bar,[{name:'Riesgo',labels:['ALTO','MEDIO','BAJO'],values:[u.risks.ALTO||0,u.risks.MEDIO||0,u.risks.BAJO||0]}],{x:0.7,y:1.15,w:4.0,h:2.7,showTitle:true,title:'Nivel de riesgo',showLegend:false,chartColors:[C.red,C.amber,C.green],varyColors:true,showValue:true});
    const causes=u.causes.slice(0,10);slide.addChart(pptx.ChartType.bar,[{name:'RACS',labels:causes.map(x=>x.name),values:causes.map(x=>x.total)}],{x:4.9,y:1.15,w:7.7,h:4.95,showTitle:true,title:'Principales causas normalizadas',showLegend:false,chartColors:[C.teal],showValue:true,catAxisLabelFontSize:8,valAxisLabelFontSize:8});
    slide.addText('RÉCORD DE PROBLEMAS',{x:0.75,y:4.15,w:3.8,h:0.3,fontSize:16,bold:true,color:C.navy,margin:0});const table=[['TIPO','ALTO','MEDIO','BAJO','TOTAL'],['ACTOS',u.rows.filter(r=>r.report_type==='ACTO SUBESTANDAR'&&r.risk_level==='ALTO').length,u.rows.filter(r=>r.report_type==='ACTO SUBESTANDAR'&&r.risk_level==='MEDIO').length,u.rows.filter(r=>r.report_type==='ACTO SUBESTANDAR'&&r.risk_level==='BAJO').length,u.acts],['CONDICIONES',u.rows.filter(r=>r.report_type!=='ACTO SUBESTANDAR'&&r.risk_level==='ALTO').length,u.rows.filter(r=>r.report_type!=='ACTO SUBESTANDAR'&&r.risk_level==='MEDIO').length,u.rows.filter(r=>r.report_type!=='ACTO SUBESTANDAR'&&r.risk_level==='BAJO').length,u.conditions]];slide.addTable(table,{x:0.7,y:4.55,w:4.0,h:1.25,border:{type:'solid',color:C.gray,pt:1},fill:C.white,color:C.ink,fontSize:9,bold:false,rowH:0.3,margin:0.05,autoFit:false});footer(slide);
    slide=pptx.addSlide();addTitle(slide,`RACS LEVANTAMIENTO · ${u.name}`,filtersLabel);const detail=u.rows.slice(0,12).map(r=>[text(r.report_code),text(r.reporter_name),text(r.location),text(r.reporting_area),text(r.report_date).slice(0,10),text(r.risk_level),text(r.cause_subtype||r.deviation_type),text(r.description).slice(0,90),text(r.supervisor_name),r.status==='LEVANTADO'?'SI':'NO']);slide.addTable([['RAC','REPORTANTE','LUGAR','ÁREA','FECHA','RIESGO','CAUSA','DESCRIPCIÓN','RESPONSABLE','LEV.'],...detail],{x:0.25,y:1.0,w:12.83,h:5.95,border:{type:'solid',color:'CBD5E1',pt:0.6},fill:C.white,color:C.ink,fontSize:6.7,margin:0.025,autoFit:false,colW:[0.8,1.05,1.1,0.95,0.7,0.55,1.2,3.15,1.05,0.45],rowH:0.36,bold:false});footer(slide);
  }
  slide=pptx.addSlide();slide.background={color:C.navy};slide.addText('GESTIÓN SSOMA BASADA EN DATOS',{x:1,y:2.2,w:11.3,h:0.7,fontSize:34,bold:true,color:C.amber,align:'center'});slide.addText('CAPSAN6',{x:1,y:3.15,w:11.3,h:0.5,fontSize:26,bold:true,color:C.white,align:'center'});slide.addText('FIN DEL REPORTE EJECUTIVO',{x:1,y:4.0,w:11.3,h:0.3,fontSize:15,color:C.mint,align:'center'});
  return pptx.write({outputType:'nodebuffer'});
}

export async function buildRacExecutiveExcel(rows,filtersLabel,workerCounts={}){
  const data=summarizeRacs(rows,workerCounts);const wb=new ExcelJS.Workbook();wb.creator='CAPSAN6';const dash=wb.addWorksheet('RESUMEN EJECUTIVO',{views:[{showGridLines:false}]});dash.columns=Array.from({length:10},()=>({width:18}));dash.mergeCells('A1:J2');dash.getCell('A1').value='REPORTE EJECUTIVO SSOMA · RACS';dash.getCell('A1').font={size:22,bold:true,color:{argb:C.white}};dash.getCell('A1').fill={type:'pattern',pattern:'solid',fgColor:{argb:C.navy}};dash.getCell('A1').alignment={horizontal:'center',vertical:'middle'};dash.mergeCells('A3:J3');dash.getCell('A3').value=filtersLabel;dash.getCell('A3').alignment={horizontal:'center'};
  const cards=[['TOTAL RACS',data.summary.total],['ACTOS',data.summary.acts],['CONDICIONES',data.summary.conditions],['ALTO POTENCIAL',data.summary.high],['% LEVANTAMIENTO',`${data.summary.closurePercent}%`]];cards.forEach(([t,v],idx)=>{const c=1+idx*2;dash.mergeCells(5,c,5,c+1);dash.mergeCells(6,c,7,c+1);const a=dash.getCell(5,c);a.value=t;a.font={bold:true,color:{argb:C.white}};a.fill={type:'pattern',pattern:'solid',fgColor:{argb:idx===3?C.red:idx===4?C.green:C.teal}};a.alignment={horizontal:'center'};const b=dash.getCell(6,c);b.value=v;b.font={size:20,bold:true,color:{argb:C.ink}};b.alignment={horizontal:'center',vertical:'middle'};});
  let row=10;dash.getCell(row,1).value='UNIDADES DE NEGOCIO';dash.getCell(row,1).font={bold:true,size:14};row++;['Unidad','Personal','RACS','RACS/Trabajador','Actos','Condiciones','Alto','Levantados','Pendientes','% Lev.'].forEach((h,i)=>dash.getCell(row,i+1).value=h);dash.getRow(row).font={bold:true,color:{argb:C.white}};dash.getRow(row).fill={type:'pattern',pattern:'solid',fgColor:{argb:C.navy}};for(const u of data.units){row++;[u.name,u.workers,u.total,u.reportRate,u.acts,u.conditions,u.high,u.lifted,u.pending,`${u.closurePercent}%`].forEach((v,i)=>dash.getCell(row,i+1).value=v);}dash.autoFilter={from:{row:11,column:1},to:{row:row,column:10}};
  const base=wb.addWorksheet('BASE RACS');base.columns=[['RAC','report_code',18],['N° origen','source_report_number',14],['Unidad','business_unit',24],['Fecha','report_date',13],['Área reportante','reporting_area',22],['Reportante','reporter_name',26],['Tipo reportante','reporter_type',18],['Lugar','location',28],['Área reportada','reported_area',22],['Riesgo','risk_level',12],['Tipo','report_type',24],['Tipo de causa','cause_category',24],['Subtipo / causa normalizada','cause_subtype',34],['Descripción','description',60],['Supervisor','supervisor_name',26],['Acción correctiva','corrective_action',45],['Estado','status',24],['Avance %','progress_percent',12],['Ambiental','environmental_flag',12]].map(([header,key,width])=>({header,key,width}));base.views=[{state:'frozen',ySplit:1}];base.getRow(1).font={bold:true,color:{argb:C.white}};base.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:C.navy}};rows.forEach(r=>base.addRow(r));base.autoFilter={from:'A1',to:'S1'};
  const sup=wb.addWorksheet('SUPERVISORES');sup.columns=[{header:'Unidad',key:'unit',width:28},{header:'Supervisor',key:'name',width:32},{header:'RACS',key:'total',width:12},{header:'Levantados',key:'lifted',width:14},{header:'% Lev.',key:'pct',width:12}];sup.getRow(1).font={bold:true,color:{argb:C.white}};sup.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:C.teal}};for(const u of data.units)for(const s of u.supervisors){const lifted=u.rows.filter(r=>(text(r.supervisor_name)||'SIN ASIGNAR')===s.name&&r.status==='LEVANTADO').length;sup.addRow({unit:u.name,name:s.name,total:s.total,lifted,pct:`${pct(lifted,s.total)}%`});}
  const causes=wb.addWorksheet('CAUSAS');causes.columns=[{header:'Unidad',key:'unit',width:28},{header:'Causa normalizada',key:'name',width:48},{header:'RACS',key:'total',width:12}];causes.getRow(1).font={bold:true,color:{argb:C.white}};causes.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:C.amber}};for(const u of data.units)for(const c of u.causes)causes.addRow({unit:u.name,...c});
  return wb.xlsx.writeBuffer();
}
